import { Project } from '@/types';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const PdfService = {
    async exportProject(project: Project) {
        const html = generateHtml(project);
        try {
            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } catch (e) {
            console.error('Failed to export PDF', e);
        }
    }
};

function generateHtml(project: Project) {
    const date = new Date(project.createdAt).toLocaleDateString();
    const inputs = Object.entries(project.data)
        .map(([k, v]) => `<tr><td><strong>${k}</strong></td><td>${v}</td></tr>`)
        .join('');

    const results = Object.entries(project.result)
        .map(([k, v]) => {
            const val = typeof v === 'number' ? v.toFixed(2) : v;
            return `<tr><td><strong>${k}</strong></td><td>${val}</td></tr>`;
        })
        .join('');

    return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
          h1 { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
          h2 { margin-top: 30px; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          td { padding: 8px 0; border-bottom: 1px solid #eee; }
          strong { color: #555; }
          .note { background: #f9f9f9; padding: 15px; border-radius: 5px; margin-top: 20px; }
          .footer { margin-top: 50px; font-size: 12px; color: #999; text-align: center; }
        </style>
      </head>
      <body>
        <h1>${project.name}</h1>
        <p><strong>Date:</strong> ${date}</p>
        <p><strong>Type:</strong> ${project.type.toUpperCase()}</p>

        <h2>Inputs</h2>
        <table>${inputs}</table>

        <h2>Result</h2>
        <table>${results}</table>

        ${project.note ? `<h2>Notes</h2><div class="note">${project.note}</div>` : ''}

        <div class="footer">
          Generated by Concrete & Flooring Estimator
        </div>
      </body>
    </html>
  `;
}
